name: Markdown Checker, and Linter
on: [push, pull_request]

jobs:
  # spelling: 
  #   name: Spell Checker
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - name: Checkout the repository
  #     uses: actions/checkout@v1
      
  #   - name: Checking spelling
  #     uses: rojopolis/spellcheck-github-actions@0.14.0
  #     with:
  #       task_name: Markdown
  #       config_path: config/spellcheck.yaml
      
  validate_links:
    name: Markdown links verifier
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Validate links
      uses: Youssef1313/markdown-links-verifier@v0.1.2
      
  linting:
    name: Markdown Linter
    runs-on: ubuntu-latest
    
    steps:
      - name: Linting Markdown
        uses: articulate/actions-markdownlint@v1
