name: Markdown Checker, and Linter
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # spelling: 
  #   name: Spell Checker
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - name: Checkout the repository
  #     uses: actions/checkout@v1
      
  #   - name: Checking spelling
  #     uses: rojopolis/spellcheck-github-actions@0.14.0
  #     with:
  #       task_name: Markdown
  #       config_path: config/spellcheck.yaml
      
  validate_links:
    name: Markdown links verifier
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Validate links
      uses: Youssef1313/markdown-links-verifier@v0.1.2
      
  linting:
    name: Markdown Linter
    runs-on: ubuntu-latest
    
    steps:
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          config_file: ".config/markdownlint.yaml"
