name: Markdown Linter
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:      
  linting:
    name: Markdown Linter
    runs-on: ubuntu-latest
    
    steps:
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v2
        with:
          files: "**/*.md"
          config_file: ".config/markdownlint.yaml"
